{
 "title": "web-server",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) without (cpu) * 100",
     "legendFormat": "mode={{mode}}"
    }
   ]
  },
  {
   "title": "USAGE RAM (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes )/ 999998256)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX connection",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Свободное место на диске (Gb)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes/999998256",
     "legendFormat": "{{device}}, {{fstype}}, {{mountpoint}}"
    }
   ]
  },
  {
   "title": "NGINX UP",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 6 },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}