---
# В play 1 установка docker производится через модуль ansible-shell

- name: install docker # название первого play
  hosts: monitoring # группа хостов, над которой будем выполнять изменения
  become: true # выполнять команды от суперпользователя

  tasks: # описываем запросы первого play
  - name: install docker # зададим имя
    ansible.builtin.shell: |
      yum install -y yum-utils &&
      yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo &&
      yum install -y --allowerasing docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    tags: install_docker
    # --allowerasing - заменить пакеты, если уже установлены

  - name: enable docker
    ansible.builtin.systemd_service: # модуль запуска
      name: docker.service
      state: started # запустить
      enabled: true # добавить в автозапуск
    tags: run_docker_monitoring

  tags: install_docker_monitoring_play

- name: monitoring
  hosts: monitoring
  become: true

  tasks:
  - name: wget docker-compose
    ansible.builtin.shell: |
      cd /home/vagrant/ && 
      wget https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 &&
      cp docker-compose-Linux-x86_64 /vagrant/monitoring/configs/
    tags: wget_docker_compose

  - name: start monitoring soft
    community.docker.docker_compose_v2:
      project_src: /vagrant/monitoring/configs/
      files:
      - docker-compose.yml
      state: present
    tags: start_monitoring_soft

  - name: down eth0
    ansible.builtin.shell: |
      ifconfig eth0 down
    tags: monitoring_eth0_down

  tags: monitoring