---
- name: postgresql
  hosts: pgslave
  become: true

  tasks:
  - name: delete configs
    ansible.builtin.shell: |
      rm -rf /var/lib/pgsql/data/pg_hba.conf &&
      rm -rf /var/lib/pgsql/data/postgresql.conf
    tags: delete_slave_configs

  - name: copy pg_hba
    ansible.builtin.copy:
      src: /etc/ansible/files/pg_hba.slave.conf
      dest: /var/lib/pgsql/data/pg_hba.conf
      owner: postgres
      group: postgres
      mode: '0600'
    tags: copy_slave_pg_hba

  - name: copy postgresql.conf
    ansible.builtin.copy:
      src: /etc/ansible/files/postgresql.slave.conf
      dest: /var/lib/pgsql/data/postgresql.conf
      owner: postgres
      group: postgres
      mode: '0600'
    tags: copy_slave_postgresql.conf

  - name: replica settings
    ansible.builtin.shell: |
      sudo mkdir ~/pgbackup &&
      sudo cp /var/lib/pgsql/data/ ~/pgbackup/ &&
      sudo rm -rf /var/lib/pgsql/data/* &&
      pg_basebackup -P -R -X stream -c fast -h 10.200.1.4 -U repuser -D /var/lib/pgsql/data/ &&
      sudo chmod 777 /var/lib/pgsql/data/* &&
      sudo chmod 777 /var/lib/pgsql/data/*/* &&
      sudo chmod 777 /var/lib/pgsql/data/*/*/* &&
      sudo chmod 777 /var/lib/pgsql/data/*/*/*/* &&
      sudo sed -i 's/10.200.1.4/10.200.1.6/g' /var/lib/pgsql/data/postgresql.conf &&
      sudo systemctl start postgresql.service
    tags: replica_settings

  - name: restart_db
    ansible.builtin.service:
      name: postgresql
      state: restarted
    tags: restart_postgres

  tags: postgresql_settings