scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets:
      - 172.16.1.1:9100
      - 172.16.1.1:9113
      
rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "172.20.0.20:9093"
