scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets:
      - 10.200.1.4:9100
      - 10.200.1.4:9113

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "172.20.0.20:9093"